import type { Track } from './schema.ts'

export const tracks: Track[] = [
  {
    id: 'foundations',
    title: 'Foundations',
    blurb: 'How a program is built and the language core',
    icon: '{ }',
    topicIds: [
      'compilation',
      'preprocessor',
      'types',
      'cv-qualifiers',
      'literals',
      'operators',
      'control-flow',
      'scope-namespaces',
      'conversions',
    ],
  },
  {
    id: 'memory',
    title: 'Memory & values',
    blurb: 'Where objects live and how they move',
    icon: '[#]',
    topicIds: [
      'stack-heap',
      'pointers-refs',
      'arrays',
      'layout',
      'value-categories',
      'copy-move',
      'new-delete',
    ],
  },
  {
    id: 'functions',
    title: 'Functions',
    blurb: 'Calling, overloading, and callables',
    icon: 'fn',
    topicIds: ['functions', 'overloading', 'pass-by', 'lambdas', 'constexpr'],
  },
  {
    id: 'classes',
    title: 'Classes & OOP',
    blurb: 'Types you design, and how they inherit',
    icon: 'C++',
    topicIds: [
      'classes',
      'special-members',
      'lifetime',
      'inheritance',
      'polymorphism',
      'operator-overloading',
    ],
  },
  {
    id: 'templates',
    title: 'Templates',
    blurb: 'Generic code generated at compile time',
    icon: '<T>',
    topicIds: ['templates', 'specialization', 'type-traits'],
  },
  {
    id: 'errors',
    title: 'Errors',
    blurb: 'Exceptions, noexcept, and failure paths',
    icon: '!!',
    topicIds: ['exceptions', 'error-handling'],
  },
  {
    id: 'stdlib',
    title: 'Standard library',
    blurb: 'Containers, algorithms, I/O, and more',
    icon: 'std',
    topicIds: [
      'string',
      'containers',
      'iterators',
      'algorithms',
      'smart-pointers',
      'iostreams',
      'chrono',
      'concurrency',
    ],
  },
  {
    id: 'idioms',
    title: 'Idioms & pitfalls',
    blurb: 'How working C++ is actually written',
    icon: '</>',
    topicIds: [
      'patterns',
      'rule-of-zero',
      'undefined-behavior',
      'const-correctness',
      'pitfalls',
    ],
  },
]
